project_id = "hbyzmuxkgsogbxhykhhu"

[auth]
site_url = "https://wt7planejamento.lovable.app"
additional_redirect_urls = ["https://wt7planejamento.lovable.app/reset-password"]

[functions.wisely-ai]
verify_jwt = false

[functions.naval-embed]
verify_jwt = true

[functions.naval-ingest]
verify_jwt = true


[functions.pluggy-sync]
verify_jwt = true

[functions.extract-celesc-invoice]
verify_jwt = true
